[build]
  command = "pip install -r requirements.txt && npm i && cp app.py src_functions/ && npx netlify-lambda build src_functions"
  publish = "dist"
  functions = "src_functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  FLASK_ENV = "development"

[functions]
  directory = "src_functions"
  node_bundler = "esbuild"


