[build]
  command = "pip install -r requirements.txt && npm i && cp app.py src_functions/ && npx netlify-lambda build src_functions -d functions_build"
  publish = "dist"
  functions = "functions_build"

[build.environment]
  PYTHON_VERSION = "3.8"
  FLASK_ENV = "development"

[functions]
  directory = "functions_build"
  node_bundler = "esbuild"

