[build]
  command = "pip install -r requirements.txt && npm i && npx webpack --config webpack.functions.js"
  publish = "dist"

[functions]
  directory = "functions_build"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
