[build]
  publish = "dist"
  command = "pip install -r requirements.txt && npm i && cp ov_crawl/* netlify_functions/ && npx netlify-lambda build netlify_functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify_functions"
  node_bundler = "esbuild"

[context.production.environment]
  FLASK_ENV = "production"
