[build]
  command = "pip install -r requirements.txt && npm i && cp src_functions/* netlify_functions/ && npx netlify-lambda build src_functions"
  publish = "dist"
  functions = "netlify_functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  FLASK_ENV = "development"

[[functions]]
  src = "src_functions/app.py"
  name = "app"
  runtime = "python3.8"

[functions]
  node_bundler = "esbuild"

