[build]
  command = "pip install -r requirements.txt && npm i && npx netlify-lambda build src_functions --config webpack.functions.js"
  publish = "dist"
  functions = "functions_build"

[build.environment]
  PYTHON_VERSION = "3.8"
  FLASK_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions_build"
  node_bundler = "esbuild"
